### ISSUE TITLE
Start trying to implement the create an account method

### ISSUE THREAD

**Issue by Vinceserr** [Vinceserr/CSC325-Team6#4]

**Comment by ZuxinChen** [comment]
I make the sign-up system work. It can create account, but it cannot save account data after system exit. Has anyone created a database?

**Comment by Vinceserr** [comment]
No, not yet I'm waiting for her to start teaching Firebase since I don't know how to use it yet and she wants us to use it for the project but, as soon as I do I'll start working on it.

**Comment by Xxbrian6** [comment]
completed
