### ISSUE TITLE
new schedule idea for event list 

### ISSUE THREAD

**Issue by ZuxinChen** [Vinceserr/CSC325-Team6#8]
add event on list which right of calendar, only the user chooses the day that event will show on the list.

**Comment by Xxbrian6** [comment]
good idea, create a new branch from Master and work on the issue. make a pull request so we can test it . If someone else agrees with your code then u can merge into the main branch.

**Comment by ZuxinChen** [comment]
the prototype version 1.0 is complete.

**Comment by Xxbrian6** [comment]
UI looks good , but it is throwing an error when adding more than 2 events in different months.

<img width="889" alt="sc" src="https://github.com/Vinceserr/CSC325-Team6/assets/143741581/f2a9d1b5-6bd5-402d-85ab-b656ba972ec9">

**Comment by ZuxinChen** [comment]
this issue has been solved. using my new push code.

**Comment by Xxbrian6** [comment]
create a merge request and merge your branch  to the Master branch
